apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-go
  labels:
    app: hello-go
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-go
  template:
    metadata:
      name: hello-go
      labels:
        app: hello-go
    spec:
      containers:
      - name: hello-go
        image: mhrocha1997/hello-go:v6.4
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
            cpu: "250m"

        startupProbe:
          httpGet:
            path: /healthz
            port: 8000
          periodSeconds: 3
          failureThreshold: 30
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8000
          periodSeconds: 3
          failureThreshold: 1
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8000
          periodSeconds: 5
          failureThreshold: 3
          timeoutSeconds: 10
          successThreshold: 1
        envFrom:
          - configMapRef:
              name: hello-go-env
          - secretRef:
              name: hello-go-secret
        volumeMounts:
          - name: config-volume
            mountPath: /go/env
          - name: hello-go-pvc-volume
            mountPath: /go/pvc
      volumes:
        - name: hello-go-pvc-volume
          persistentVolumeClaim:
            claimName: hello-go-pvc
        - name: config-volume
          configMap:
            name: hello-go-family
            items: 
              - key: members
                path: "members.txt"