apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-go
  labels:
    app: hello-go
spec:
  replicas: 10
  selector:
    matchLabels:
      app: hello-go
  template:
    metadata:
      name: hello-go
      labels:
        app: hello-go
    spec:
      containers:
      - name: hello-go
        image: mhrocha1997/hello-go:v3
        # env: 
        #   - name: NAME
        #     value: "Marcelo"
        #   - name: AGE
        #     value: "26"
        envFrom:
          - configMapRef:
              name: hello-go-env